In [26]:
import os
import pickle
import numpy as np

In [39]:
(train_data==train_data_2).sum()

900524

In [40]:
train_data.shape[0]*train_data.shape[1]

900524

In [33]:
train_data_2

array([[0.06383 , 0.072519, 0.082098, ..., 0.065868, 0.      , 0.      ],
       [0.12766 , 0.067748, 0.082098, ..., 0.077844, 0.      , 0.      ],
       [0.106383, 0.131679, 0.099202, ..., 0.083832, 0.      , 0.      ],
       ...,
       [0.329787, 0.295802, 0.323831, ..., 0.215569, 0.      , 0.      ],
       [0.308511, 0.229962, 0.303307, ..., 0.213573, 0.      , 0.      ],
       [0.329787, 0.204198, 0.287343, ..., 0.219561, 0.      , 0.      ]],
      dtype=float32)

In [43]:
np.loadtxt(os.path.join(dataset_folder, "labels.txt"), delimiter=",")

array([0., 0., 0., ..., 0., 0., 0.])

In [44]:
f = open("datasets/system_1/processsed/labels.pkl", "rb")
aa = pickle.load(f).reshape((-1))
f.close()

In [4]:
from os import path

array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

In [7]:
import numpy as np

In [9]:
file_list

['machine-1-1.txt',
 'machine-1-2.txt',
 'machine-1-3.txt',
 'machine-1-4.txt',
 'machine-1-5.txt',
 'machine-1-6.txt',
 'machine-1-7.txt',
 'machine-1-8.txt',
 'machine-2-1.txt',
 'machine-2-2.txt',
 'machine-2-3.txt',
 'machine-2-4.txt',
 'machine-2-5.txt',
 'machine-2-6.txt',
 'machine-2-7.txt',
 'machine-2-8.txt',
 'machine-2-9.txt',
 'machine-3-1.txt',
 'machine-3-10.txt',
 'machine-3-11.txt',
 'machine-3-2.txt',
 'machine-3-3.txt',
 'machine-3-4.txt',
 'machine-3-5.txt',
 'machine-3-6.txt',
 'machine-3-7.txt',
 'machine-3-8.txt',
 'machine-3-9.txt']